version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Default RabbitMQ port for messaging
      - "15672:15672"  # Management console
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent data storage
      - rabbitmq_logs:/var/log/rabbitmq # Persistent log storage
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  producer:
    image: message-brokers:latest
    container_name: producer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      MQ_HOST: rabbitmq
      MQ_PORT: 5672
      MQ_USER: test
      MQ_PASSWORD: 123456
    command: uv run python ./src/producer.py
  consumer:
    image: message-brokers:latest
    container_name: consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      MQ_HOST: rabbitmq
      MQ_PORT: 5672
      MQ_USER: test
      MQ_PASSWORD: 123456
    command: uv run python ./src/consumer.py

volumes:
  rabbitmq_data:
  rabbitmq_logs:
